import Head from "next/head";
import Header from "../components/Header";
import Main from "../components/Main";
import requests from "../utils/requests";


export default function Home({ movies }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main movies={movies} />
    </div>
  );
}

export async function getServerSideProps() {
  const trendingMovies = await fetch(requests.fetchTrending).then((res) =>
    res.json()
  );
  const topRatedMovies = await fetch(requests.fetchTopRated).then((res) =>
    res.json()
  );
  const actionMovies = await fetch(requests.fetchActionMovies).then((res) =>
    res.json()
  );
  const comedyMovies = await fetch(requests.fetchComedyMovies).then((res) =>
    res.json()
  );
  const documentaries = await fetch(requests.fetchDocumentaries).then((res) =>
    res.json()
  );
  const horrorMovies = await fetch(requests.fetchHorrorMovies).then((res) =>
    res.json()
  );
  const romanceMovies = await fetch(requests.fetchRomanceMovies).then((res) =>
    res.json()
  );

  return {
    props: {
      name: "niket",
      movies: {
        "Trending Movies": trendingMovies,
        "Top Rated Movies": topRatedMovies,
        "Action Movies": actionMovies,
        "Comedy Movies": comedyMovies,
        // Documentaries: documentaries,
        "Horror Movies": horrorMovies,
        "Romance Movies": romanceMovies,
      },
    },
  };
}
